[project]
name = "class-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.12.2",
    "requests>=2.32.4",
    "rich>=14.1.0",
]
